# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: EsrpRelease@2
  inputs:
    ConnectedServiceName: 'ESRP Release to Maven Central'
    Intent: 'PackageDistribution'
    ContentType: 'Maven'
    PackageLocation: 'target'
    Owners: 'simonabykov@microsoft.com'
    Approvers: 'nickbrabbs@microsoft.com'
    ServiceEndpointUrl: 'https://api.esrp.microsoft.com'
    MainPublisher: 'ESRPRELPACMAN'
    DomainTenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47'